services:
  notebook:
    build:
      context: notebook
      dockerfile: Dockerfile
    ports:
      - "8888:8888"
    networks:
      - api
    depends_on:
      - api
    volumes:
      - "./notebook/files:/app/files"
    environment:
      - API_URL=http://api:8000
  api:
    build:
      context: API
      dockerfile: Dockerfile
    networks:
      - api
    restart: on-failure

networks:
  api: