[project]
authors = ["Antoine DESRUET <antoine.desruet@epitech.eu>"]
channels = ["https://conda.modular.com/max-nightly", "https://conda.modular.com/max", "https://repo.prefix.dev/modular-community", "conda-forge"]
name = "notebook"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
max = "*"
jupyterlab = ">=4.4.0,<5"
pandas = ">=2.2.2,<3"
matplotlib = ">=3.9.2,<4"
