services:
  api:
    restart: on-failure
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    networks:
      - backend
    depends_on:
      - db
    env_file:
      - .env
      
  db:
    image: postgres:14.18
    env_file:
      - .env
    networks:
      - backend
    restart: always
    volumes:
      - "database_volume:/var/lib/postgresql"

  adminer:
    image: adminer
    restart: always
    networks:
      - backend
    ports:
      - 8080:8080
    environment:
      ADMINER_DEFAULT_SERVER: "db"
      ADMINER_DESIGN: dracula
      ADMINER_PLUGINS: "config dark-switcher backward-keys"

networks:
  backend:
   
volumes:
  database_volume: