services:
  api:
    restart: on-failure
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000-8003:8000"
    networks:
      - backend
    depends_on:
      - db
    env_file:
      - .env
    deploy:
      replicas: 3

      
  db:
    image: postgres:14.18
    env_file:
      - .env
    networks:
      - backend
    restart: always
    volumes:
      - "database_volume:/var/lib/postgresql"

networks:
  backend:
   
volumes:
  database_volume: