# Install uv https://docs.astral.sh/uv/guides/integration/docker/#intermediate-layers
FROM python:3.13.2

COPY --from=ghcr.io/astral-sh/uv:0.6.12 /uv /uvx /bin/

# Change the working directory to the `app` directory
WORKDIR /app

# Install dependencies
RUN --mount=type=cache,target=/root/.cache/uv \
    --mount=type=bind,source=uv.lock,target=uv.lock \
    --mount=type=bind,source=pyproject.toml,target=pyproject.toml \
    uv sync --locked --no-install-project --no-editable

# Copy the project into the intermediate image
COPY . /app

# Sync the project
RUN --mount=type=cache,target=/root/.cache/uv \
    uv sync --locked --no-editable --compile-bytecode

EXPOSE 8000 5678

CMD ["/app/.venv/bin/debugpy", "--listen","0.0.0.0:5678", "/app/.venv/bin/fastapi" ,"dev", "app/main.py", "--port", "8000", "--host", "0.0.0.0"]