services:
  api_debug:
    restart: on-failure
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "8000:8000"
      - "5678:5678"
    networks:
      - backend
    depends_on:
      - db
    env_file:
      - .env
    develop:
      watch:
        - action: sync
          path: .
          target: /app
          ignore:
            - .venv/
        - action: rebuild
          path: ./pyproject.toml
    healthcheck:
      test: curl --fail http://localhost:8000/healthcheck || exit 1
      start_period: 60s
  db:
    image: postgres:14.18
    env_file:
      - .env
    networks:
      - backend
    restart: always
    volumes:
      - "database_volume:/var/lib/postgresql"
  adminer:
    networks:
      - backend
    image: adminer:latest
    ports:
      - "8080:8080"

networks:
  backend:
    
volumes:
  database_volume: